//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("MojaModel", "FK_AccessLog_Cardholder", "Cardholder", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(konekcija.Cardholder), "AccessLog", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(konekcija.AccessLog), true)]
[assembly: EdmRelationshipAttribute("MojaModel", "FK_Card_Cardholder", "Cardholder", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(konekcija.Cardholder), "Card", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(konekcija.Card), true)]
[assembly: EdmRelationshipAttribute("MojaModel", "FK_CardholderShift_Cardholder", "Cardholder", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(konekcija.Cardholder), "CardholderShift", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(konekcija.CardholderShift), true)]
[assembly: EdmRelationshipAttribute("MojaModel", "FK_Exception_Cardholder", "Cardholder", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(konekcija.Cardholder), "LogException", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(konekcija.LogException), true)]
[assembly: EdmRelationshipAttribute("MojaModel", "FK_Holiday_Cardholder", "Cardholder", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(konekcija.Cardholder), "Holiday", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(konekcija.Holiday), true)]
[assembly: EdmRelationshipAttribute("MojaModel", "FK_NonWorkingDays_Cardholder", "Cardholder", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(konekcija.Cardholder), "NonWorkingDay", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(konekcija.NonWorkingDay), true)]
[assembly: EdmRelationshipAttribute("MojaModel", "FK_CardholderShift_Shift", "Shift", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(konekcija.Shift), "CardholderShift", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(konekcija.CardholderShift), true)]

#endregion

namespace konekcija
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MojaEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MojaEntities object using the connection string found in the 'MojaEntities' section of the application configuration file.
        /// </summary>
        public MojaEntities() : base("name=MojaEntities", "MojaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MojaEntities object.
        /// </summary>
        public MojaEntities(string connectionString) : base(connectionString, "MojaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MojaEntities object.
        /// </summary>
        public MojaEntities(EntityConnection connection) : base(connection, "MojaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AccessLog> AccessLogs
        {
            get
            {
                if ((_AccessLogs == null))
                {
                    _AccessLogs = base.CreateObjectSet<AccessLog>("AccessLogs");
                }
                return _AccessLogs;
            }
        }
        private ObjectSet<AccessLog> _AccessLogs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Card> Cards
        {
            get
            {
                if ((_Cards == null))
                {
                    _Cards = base.CreateObjectSet<Card>("Cards");
                }
                return _Cards;
            }
        }
        private ObjectSet<Card> _Cards;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Cardholder> Cardholders
        {
            get
            {
                if ((_Cardholders == null))
                {
                    _Cardholders = base.CreateObjectSet<Cardholder>("Cardholders");
                }
                return _Cardholders;
            }
        }
        private ObjectSet<Cardholder> _Cardholders;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CardholderShift> CardholderShifts
        {
            get
            {
                if ((_CardholderShifts == null))
                {
                    _CardholderShifts = base.CreateObjectSet<CardholderShift>("CardholderShifts");
                }
                return _CardholderShifts;
            }
        }
        private ObjectSet<CardholderShift> _CardholderShifts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Holiday> Holidays
        {
            get
            {
                if ((_Holidays == null))
                {
                    _Holidays = base.CreateObjectSet<Holiday>("Holidays");
                }
                return _Holidays;
            }
        }
        private ObjectSet<Holiday> _Holidays;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LogException> LogExceptions
        {
            get
            {
                if ((_LogExceptions == null))
                {
                    _LogExceptions = base.CreateObjectSet<LogException>("LogExceptions");
                }
                return _LogExceptions;
            }
        }
        private ObjectSet<LogException> _LogExceptions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NonWorkingDay> NonWorkingDays
        {
            get
            {
                if ((_NonWorkingDays == null))
                {
                    _NonWorkingDays = base.CreateObjectSet<NonWorkingDay>("NonWorkingDays");
                }
                return _NonWorkingDays;
            }
        }
        private ObjectSet<NonWorkingDay> _NonWorkingDays;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Shift> Shifts
        {
            get
            {
                if ((_Shifts == null))
                {
                    _Shifts = base.CreateObjectSet<Shift>("Shifts");
                }
                return _Shifts;
            }
        }
        private ObjectSet<Shift> _Shifts;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AccessLogs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAccessLogs(AccessLog accessLog)
        {
            base.AddObject("AccessLogs", accessLog);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Cards EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCards(Card card)
        {
            base.AddObject("Cards", card);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Cardholders EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCardholders(Cardholder cardholder)
        {
            base.AddObject("Cardholders", cardholder);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CardholderShifts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCardholderShifts(CardholderShift cardholderShift)
        {
            base.AddObject("CardholderShifts", cardholderShift);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Holidays EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHolidays(Holiday holiday)
        {
            base.AddObject("Holidays", holiday);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LogExceptions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLogExceptions(LogException logException)
        {
            base.AddObject("LogExceptions", logException);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NonWorkingDays EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNonWorkingDays(NonWorkingDay nonWorkingDay)
        {
            base.AddObject("NonWorkingDays", nonWorkingDay);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Shifts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToShifts(Shift shift)
        {
            base.AddObject("Shifts", shift);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MojaModel", Name="AccessLog")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AccessLog : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AccessLog object.
        /// </summary>
        /// <param name="logID">Initial value of the LogID property.</param>
        public static AccessLog CreateAccessLog(global::System.Int32 logID)
        {
            AccessLog accessLog = new AccessLog();
            accessLog.LogID = logID;
            return accessLog;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LogID
        {
            get
            {
                return _LogID;
            }
            set
            {
                if (_LogID != value)
                {
                    OnLogIDChanging(value);
                    ReportPropertyChanging("LogID");
                    _LogID = StructuralObject.SetValidValue(value, "LogID");
                    ReportPropertyChanged("LogID");
                    OnLogIDChanged();
                }
            }
        }
        private global::System.Int32 _LogID;
        partial void OnLogIDChanging(global::System.Int32 value);
        partial void OnLogIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CardCode
        {
            get
            {
                return _CardCode;
            }
            set
            {
                OnCardCodeChanging(value);
                ReportPropertyChanging("CardCode");
                _CardCode = StructuralObject.SetValidValue(value, true, "CardCode");
                ReportPropertyChanged("CardCode");
                OnCardCodeChanged();
            }
        }
        private global::System.String _CardCode;
        partial void OnCardCodeChanging(global::System.String value);
        partial void OnCardCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CardType
        {
            get
            {
                return _CardType;
            }
            set
            {
                OnCardTypeChanging(value);
                ReportPropertyChanging("CardType");
                _CardType = StructuralObject.SetValidValue(value, "CardType");
                ReportPropertyChanged("CardType");
                OnCardTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _CardType;
        partial void OnCardTypeChanging(Nullable<global::System.Int32> value);
        partial void OnCardTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ControllerID
        {
            get
            {
                return _ControllerID;
            }
            set
            {
                OnControllerIDChanging(value);
                ReportPropertyChanging("ControllerID");
                _ControllerID = StructuralObject.SetValidValue(value, "ControllerID");
                ReportPropertyChanged("ControllerID");
                OnControllerIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ControllerID;
        partial void OnControllerIDChanging(Nullable<global::System.Int32> value);
        partial void OnControllerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Direction
        {
            get
            {
                return _Direction;
            }
            set
            {
                OnDirectionChanging(value);
                ReportPropertyChanging("Direction");
                _Direction = StructuralObject.SetValidValue(value, "Direction");
                ReportPropertyChanged("Direction");
                OnDirectionChanged();
            }
        }
        private Nullable<global::System.Int32> _Direction;
        partial void OnDirectionChanging(Nullable<global::System.Int32> value);
        partial void OnDirectionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LocalTime
        {
            get
            {
                return _LocalTime;
            }
            set
            {
                OnLocalTimeChanging(value);
                ReportPropertyChanging("LocalTime");
                _LocalTime = StructuralObject.SetValidValue(value, "LocalTime");
                ReportPropertyChanged("LocalTime");
                OnLocalTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _LocalTime;
        partial void OnLocalTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnLocalTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CardholderID
        {
            get
            {
                return _CardholderID;
            }
            set
            {
                OnCardholderIDChanging(value);
                ReportPropertyChanging("CardholderID");
                _CardholderID = StructuralObject.SetValidValue(value, "CardholderID");
                ReportPropertyChanged("CardholderID");
                OnCardholderIDChanged();
            }
        }
        private Nullable<global::System.Int32> _CardholderID;
        partial void OnCardholderIDChanging(Nullable<global::System.Int32> value);
        partial void OnCardholderIDChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MojaModel", "FK_AccessLog_Cardholder", "Cardholder")]
        public Cardholder Cardholder
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cardholder>("MojaModel.FK_AccessLog_Cardholder", "Cardholder").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cardholder>("MojaModel.FK_AccessLog_Cardholder", "Cardholder").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cardholder> CardholderReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cardholder>("MojaModel.FK_AccessLog_Cardholder", "Cardholder");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cardholder>("MojaModel.FK_AccessLog_Cardholder", "Cardholder", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MojaModel", Name="Card")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Card : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Card object.
        /// </summary>
        /// <param name="cardID">Initial value of the CardID property.</param>
        public static Card CreateCard(global::System.Int32 cardID)
        {
            Card card = new Card();
            card.CardID = cardID;
            return card;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CardID
        {
            get
            {
                return _CardID;
            }
            set
            {
                if (_CardID != value)
                {
                    OnCardIDChanging(value);
                    ReportPropertyChanging("CardID");
                    _CardID = StructuralObject.SetValidValue(value, "CardID");
                    ReportPropertyChanged("CardID");
                    OnCardIDChanged();
                }
            }
        }
        private global::System.Int32 _CardID;
        partial void OnCardIDChanging(global::System.Int32 value);
        partial void OnCardIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CardNo
        {
            get
            {
                return _CardNo;
            }
            set
            {
                OnCardNoChanging(value);
                ReportPropertyChanging("CardNo");
                _CardNo = StructuralObject.SetValidValue(value, true, "CardNo");
                ReportPropertyChanged("CardNo");
                OnCardNoChanged();
            }
        }
        private global::System.String _CardNo;
        partial void OnCardNoChanging(global::System.String value);
        partial void OnCardNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CardNoIntCode
        {
            get
            {
                return _CardNoIntCode;
            }
            set
            {
                OnCardNoIntCodeChanging(value);
                ReportPropertyChanging("CardNoIntCode");
                _CardNoIntCode = StructuralObject.SetValidValue(value, true, "CardNoIntCode");
                ReportPropertyChanged("CardNoIntCode");
                OnCardNoIntCodeChanged();
            }
        }
        private global::System.String _CardNoIntCode;
        partial void OnCardNoIntCodeChanging(global::System.String value);
        partial void OnCardNoIntCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CardholderID
        {
            get
            {
                return _CardholderID;
            }
            set
            {
                OnCardholderIDChanging(value);
                ReportPropertyChanging("CardholderID");
                _CardholderID = StructuralObject.SetValidValue(value, "CardholderID");
                ReportPropertyChanged("CardholderID");
                OnCardholderIDChanged();
            }
        }
        private Nullable<global::System.Int32> _CardholderID;
        partial void OnCardholderIDChanging(Nullable<global::System.Int32> value);
        partial void OnCardholderIDChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MojaModel", "FK_Card_Cardholder", "Cardholder")]
        public Cardholder Cardholder
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cardholder>("MojaModel.FK_Card_Cardholder", "Cardholder").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cardholder>("MojaModel.FK_Card_Cardholder", "Cardholder").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cardholder> CardholderReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cardholder>("MojaModel.FK_Card_Cardholder", "Cardholder");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cardholder>("MojaModel.FK_Card_Cardholder", "Cardholder", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MojaModel", Name="Cardholder")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cardholder : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Cardholder object.
        /// </summary>
        /// <param name="cardholderID">Initial value of the CardholderID property.</param>
        public static Cardholder CreateCardholder(global::System.Int32 cardholderID)
        {
            Cardholder cardholder = new Cardholder();
            cardholder.CardholderID = cardholderID;
            return cardholder;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CardholderID
        {
            get
            {
                return _CardholderID;
            }
            set
            {
                if (_CardholderID != value)
                {
                    OnCardholderIDChanging(value);
                    ReportPropertyChanging("CardholderID");
                    _CardholderID = StructuralObject.SetValidValue(value, "CardholderID");
                    ReportPropertyChanged("CardholderID");
                    OnCardholderIDChanged();
                }
            }
        }
        private global::System.Int32 _CardholderID;
        partial void OnCardholderIDChanging(global::System.Int32 value);
        partial void OnCardholderIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true, "FirstName");
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true, "LastName");
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Gender
        {
            get
            {
                return _Gender;
            }
            set
            {
                OnGenderChanging(value);
                ReportPropertyChanging("Gender");
                _Gender = StructuralObject.SetValidValue(value, "Gender");
                ReportPropertyChanged("Gender");
                OnGenderChanged();
            }
        }
        private Nullable<global::System.Boolean> _Gender;
        partial void OnGenderChanging(Nullable<global::System.Boolean> value);
        partial void OnGenderChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MojaModel", "FK_AccessLog_Cardholder", "AccessLog")]
        public EntityCollection<AccessLog> AccessLogs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<AccessLog>("MojaModel.FK_AccessLog_Cardholder", "AccessLog");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<AccessLog>("MojaModel.FK_AccessLog_Cardholder", "AccessLog", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MojaModel", "FK_Card_Cardholder", "Card")]
        public EntityCollection<Card> Cards
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Card>("MojaModel.FK_Card_Cardholder", "Card");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Card>("MojaModel.FK_Card_Cardholder", "Card", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MojaModel", "FK_CardholderShift_Cardholder", "CardholderShift")]
        public EntityCollection<CardholderShift> CardholderShifts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CardholderShift>("MojaModel.FK_CardholderShift_Cardholder", "CardholderShift");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CardholderShift>("MojaModel.FK_CardholderShift_Cardholder", "CardholderShift", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MojaModel", "FK_Exception_Cardholder", "LogException")]
        public EntityCollection<LogException> LogExceptions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<LogException>("MojaModel.FK_Exception_Cardholder", "LogException");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<LogException>("MojaModel.FK_Exception_Cardholder", "LogException", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MojaModel", "FK_Holiday_Cardholder", "Holiday")]
        public EntityCollection<Holiday> Holidays
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Holiday>("MojaModel.FK_Holiday_Cardholder", "Holiday");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Holiday>("MojaModel.FK_Holiday_Cardholder", "Holiday", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MojaModel", "FK_NonWorkingDays_Cardholder", "NonWorkingDay")]
        public EntityCollection<NonWorkingDay> NonWorkingDays
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<NonWorkingDay>("MojaModel.FK_NonWorkingDays_Cardholder", "NonWorkingDay");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<NonWorkingDay>("MojaModel.FK_NonWorkingDays_Cardholder", "NonWorkingDay", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MojaModel", Name="CardholderShift")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CardholderShift : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CardholderShift object.
        /// </summary>
        /// <param name="cardholderShiftID">Initial value of the CardholderShiftID property.</param>
        /// <param name="cardholderID">Initial value of the CardholderID property.</param>
        /// <param name="shiftID">Initial value of the ShiftID property.</param>
        public static CardholderShift CreateCardholderShift(global::System.Int32 cardholderShiftID, global::System.Int32 cardholderID, global::System.Int32 shiftID)
        {
            CardholderShift cardholderShift = new CardholderShift();
            cardholderShift.CardholderShiftID = cardholderShiftID;
            cardholderShift.CardholderID = cardholderID;
            cardholderShift.ShiftID = shiftID;
            return cardholderShift;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CardholderShiftID
        {
            get
            {
                return _CardholderShiftID;
            }
            set
            {
                if (_CardholderShiftID != value)
                {
                    OnCardholderShiftIDChanging(value);
                    ReportPropertyChanging("CardholderShiftID");
                    _CardholderShiftID = StructuralObject.SetValidValue(value, "CardholderShiftID");
                    ReportPropertyChanged("CardholderShiftID");
                    OnCardholderShiftIDChanged();
                }
            }
        }
        private global::System.Int32 _CardholderShiftID;
        partial void OnCardholderShiftIDChanging(global::System.Int32 value);
        partial void OnCardholderShiftIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CardholderID
        {
            get
            {
                return _CardholderID;
            }
            set
            {
                OnCardholderIDChanging(value);
                ReportPropertyChanging("CardholderID");
                _CardholderID = StructuralObject.SetValidValue(value, "CardholderID");
                ReportPropertyChanged("CardholderID");
                OnCardholderIDChanged();
            }
        }
        private global::System.Int32 _CardholderID;
        partial void OnCardholderIDChanging(global::System.Int32 value);
        partial void OnCardholderIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ShiftID
        {
            get
            {
                return _ShiftID;
            }
            set
            {
                OnShiftIDChanging(value);
                ReportPropertyChanging("ShiftID");
                _ShiftID = StructuralObject.SetValidValue(value, "ShiftID");
                ReportPropertyChanged("ShiftID");
                OnShiftIDChanged();
            }
        }
        private global::System.Int32 _ShiftID;
        partial void OnShiftIDChanging(global::System.Int32 value);
        partial void OnShiftIDChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MojaModel", "FK_CardholderShift_Cardholder", "Cardholder")]
        public Cardholder Cardholder
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cardholder>("MojaModel.FK_CardholderShift_Cardholder", "Cardholder").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cardholder>("MojaModel.FK_CardholderShift_Cardholder", "Cardholder").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cardholder> CardholderReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cardholder>("MojaModel.FK_CardholderShift_Cardholder", "Cardholder");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cardholder>("MojaModel.FK_CardholderShift_Cardholder", "Cardholder", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MojaModel", "FK_CardholderShift_Shift", "Shift")]
        public Shift Shift
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Shift>("MojaModel.FK_CardholderShift_Shift", "Shift").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Shift>("MojaModel.FK_CardholderShift_Shift", "Shift").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Shift> ShiftReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Shift>("MojaModel.FK_CardholderShift_Shift", "Shift");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Shift>("MojaModel.FK_CardholderShift_Shift", "Shift", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MojaModel", Name="Holiday")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Holiday : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Holiday object.
        /// </summary>
        /// <param name="holidayID">Initial value of the HolidayID property.</param>
        public static Holiday CreateHoliday(global::System.Int32 holidayID)
        {
            Holiday holiday = new Holiday();
            holiday.HolidayID = holidayID;
            return holiday;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HolidayID
        {
            get
            {
                return _HolidayID;
            }
            set
            {
                if (_HolidayID != value)
                {
                    OnHolidayIDChanging(value);
                    ReportPropertyChanging("HolidayID");
                    _HolidayID = StructuralObject.SetValidValue(value, "HolidayID");
                    ReportPropertyChanged("HolidayID");
                    OnHolidayIDChanged();
                }
            }
        }
        private global::System.Int32 _HolidayID;
        partial void OnHolidayIDChanging(global::System.Int32 value);
        partial void OnHolidayIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LeaveDate
        {
            get
            {
                return _LeaveDate;
            }
            set
            {
                OnLeaveDateChanging(value);
                ReportPropertyChanging("LeaveDate");
                _LeaveDate = StructuralObject.SetValidValue(value, "LeaveDate");
                ReportPropertyChanged("LeaveDate");
                OnLeaveDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LeaveDate;
        partial void OnLeaveDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLeaveDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ReturnDate
        {
            get
            {
                return _ReturnDate;
            }
            set
            {
                OnReturnDateChanging(value);
                ReportPropertyChanging("ReturnDate");
                _ReturnDate = StructuralObject.SetValidValue(value, "ReturnDate");
                ReportPropertyChanged("ReturnDate");
                OnReturnDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ReturnDate;
        partial void OnReturnDateChanging(Nullable<global::System.DateTime> value);
        partial void OnReturnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NumberOfDays
        {
            get
            {
                return _NumberOfDays;
            }
            set
            {
                OnNumberOfDaysChanging(value);
                ReportPropertyChanging("NumberOfDays");
                _NumberOfDays = StructuralObject.SetValidValue(value, "NumberOfDays");
                ReportPropertyChanged("NumberOfDays");
                OnNumberOfDaysChanged();
            }
        }
        private Nullable<global::System.Int32> _NumberOfDays;
        partial void OnNumberOfDaysChanging(Nullable<global::System.Int32> value);
        partial void OnNumberOfDaysChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CardholderID
        {
            get
            {
                return _CardholderID;
            }
            set
            {
                OnCardholderIDChanging(value);
                ReportPropertyChanging("CardholderID");
                _CardholderID = StructuralObject.SetValidValue(value, "CardholderID");
                ReportPropertyChanged("CardholderID");
                OnCardholderIDChanged();
            }
        }
        private Nullable<global::System.Int32> _CardholderID;
        partial void OnCardholderIDChanging(Nullable<global::System.Int32> value);
        partial void OnCardholderIDChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MojaModel", "FK_Holiday_Cardholder", "Cardholder")]
        public Cardholder Cardholder
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cardholder>("MojaModel.FK_Holiday_Cardholder", "Cardholder").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cardholder>("MojaModel.FK_Holiday_Cardholder", "Cardholder").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cardholder> CardholderReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cardholder>("MojaModel.FK_Holiday_Cardholder", "Cardholder");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cardholder>("MojaModel.FK_Holiday_Cardholder", "Cardholder", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MojaModel", Name="LogException")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LogException : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LogException object.
        /// </summary>
        /// <param name="exceptionID">Initial value of the ExceptionID property.</param>
        public static LogException CreateLogException(global::System.Int32 exceptionID)
        {
            LogException logException = new LogException();
            logException.ExceptionID = exceptionID;
            return logException;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ExceptionID
        {
            get
            {
                return _ExceptionID;
            }
            set
            {
                if (_ExceptionID != value)
                {
                    OnExceptionIDChanging(value);
                    ReportPropertyChanging("ExceptionID");
                    _ExceptionID = StructuralObject.SetValidValue(value, "ExceptionID");
                    ReportPropertyChanged("ExceptionID");
                    OnExceptionIDChanged();
                }
            }
        }
        private global::System.Int32 _ExceptionID;
        partial void OnExceptionIDChanging(global::System.Int32 value);
        partial void OnExceptionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CardholderID
        {
            get
            {
                return _CardholderID;
            }
            set
            {
                OnCardholderIDChanging(value);
                ReportPropertyChanging("CardholderID");
                _CardholderID = StructuralObject.SetValidValue(value, "CardholderID");
                ReportPropertyChanged("CardholderID");
                OnCardholderIDChanged();
            }
        }
        private Nullable<global::System.Int32> _CardholderID;
        partial void OnCardholderIDChanging(Nullable<global::System.Int32> value);
        partial void OnCardholderIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.TimeSpan> Worktime
        {
            get
            {
                return _Worktime;
            }
            set
            {
                OnWorktimeChanging(value);
                ReportPropertyChanging("Worktime");
                _Worktime = StructuralObject.SetValidValue(value, "Worktime");
                ReportPropertyChanged("Worktime");
                OnWorktimeChanged();
            }
        }
        private Nullable<global::System.TimeSpan> _Worktime;
        partial void OnWorktimeChanging(Nullable<global::System.TimeSpan> value);
        partial void OnWorktimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> ExcIN_OUT
        {
            get
            {
                return _ExcIN_OUT;
            }
            set
            {
                OnExcIN_OUTChanging(value);
                ReportPropertyChanging("ExcIN_OUT");
                _ExcIN_OUT = StructuralObject.SetValidValue(value, "ExcIN_OUT");
                ReportPropertyChanged("ExcIN_OUT");
                OnExcIN_OUTChanged();
            }
        }
        private Nullable<global::System.Boolean> _ExcIN_OUT;
        partial void OnExcIN_OUTChanging(Nullable<global::System.Boolean> value);
        partial void OnExcIN_OUTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value, "Date");
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Date;
        partial void OnDateChanging(Nullable<global::System.DateTime> value);
        partial void OnDateChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MojaModel", "FK_Exception_Cardholder", "Cardholder")]
        public Cardholder Cardholder
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cardholder>("MojaModel.FK_Exception_Cardholder", "Cardholder").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cardholder>("MojaModel.FK_Exception_Cardholder", "Cardholder").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cardholder> CardholderReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cardholder>("MojaModel.FK_Exception_Cardholder", "Cardholder");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cardholder>("MojaModel.FK_Exception_Cardholder", "Cardholder", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MojaModel", Name="NonWorkingDay")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NonWorkingDay : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NonWorkingDay object.
        /// </summary>
        /// <param name="non_working_daysID">Initial value of the Non_working_daysID property.</param>
        /// <param name="cardholderID">Initial value of the CardholderID property.</param>
        public static NonWorkingDay CreateNonWorkingDay(global::System.Int32 non_working_daysID, global::System.Int32 cardholderID)
        {
            NonWorkingDay nonWorkingDay = new NonWorkingDay();
            nonWorkingDay.Non_working_daysID = non_working_daysID;
            nonWorkingDay.CardholderID = cardholderID;
            return nonWorkingDay;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Non_working_daysID
        {
            get
            {
                return _Non_working_daysID;
            }
            set
            {
                if (_Non_working_daysID != value)
                {
                    OnNon_working_daysIDChanging(value);
                    ReportPropertyChanging("Non_working_daysID");
                    _Non_working_daysID = StructuralObject.SetValidValue(value, "Non_working_daysID");
                    ReportPropertyChanged("Non_working_daysID");
                    OnNon_working_daysIDChanged();
                }
            }
        }
        private global::System.Int32 _Non_working_daysID;
        partial void OnNon_working_daysIDChanging(global::System.Int32 value);
        partial void OnNon_working_daysIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CardholderID
        {
            get
            {
                return _CardholderID;
            }
            set
            {
                OnCardholderIDChanging(value);
                ReportPropertyChanging("CardholderID");
                _CardholderID = StructuralObject.SetValidValue(value, "CardholderID");
                ReportPropertyChanged("CardholderID");
                OnCardholderIDChanged();
            }
        }
        private global::System.Int32 _CardholderID;
        partial void OnCardholderIDChanging(global::System.Int32 value);
        partial void OnCardholderIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TotalNWD
        {
            get
            {
                return _TotalNWD;
            }
            set
            {
                OnTotalNWDChanging(value);
                ReportPropertyChanging("TotalNWD");
                _TotalNWD = StructuralObject.SetValidValue(value, "TotalNWD");
                ReportPropertyChanged("TotalNWD");
                OnTotalNWDChanged();
            }
        }
        private Nullable<global::System.Int32> _TotalNWD;
        partial void OnTotalNWDChanging(Nullable<global::System.Int32> value);
        partial void OnTotalNWDChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MojaModel", "FK_NonWorkingDays_Cardholder", "Cardholder")]
        public Cardholder Cardholder
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cardholder>("MojaModel.FK_NonWorkingDays_Cardholder", "Cardholder").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cardholder>("MojaModel.FK_NonWorkingDays_Cardholder", "Cardholder").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cardholder> CardholderReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cardholder>("MojaModel.FK_NonWorkingDays_Cardholder", "Cardholder");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cardholder>("MojaModel.FK_NonWorkingDays_Cardholder", "Cardholder", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MojaModel", Name="Shift")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Shift : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Shift object.
        /// </summary>
        /// <param name="shiftID">Initial value of the ShiftID property.</param>
        /// <param name="shiftName">Initial value of the ShiftName property.</param>
        /// <param name="shiftMonday">Initial value of the ShiftMonday property.</param>
        /// <param name="shiftTuesday">Initial value of the ShiftTuesday property.</param>
        /// <param name="shiftWednesday">Initial value of the ShiftWednesday property.</param>
        /// <param name="shiftThuersday">Initial value of the ShiftThuersday property.</param>
        /// <param name="shiftFriday">Initial value of the ShiftFriday property.</param>
        /// <param name="shiftSaturday">Initial value of the ShiftSaturday property.</param>
        /// <param name="shiftSunday">Initial value of the ShiftSunday property.</param>
        /// <param name="workingHours">Initial value of the WorkingHours property.</param>
        /// <param name="breakTime">Initial value of the BreakTime property.</param>
        public static Shift CreateShift(global::System.Int32 shiftID, global::System.String shiftName, global::System.Boolean shiftMonday, global::System.Boolean shiftTuesday, global::System.Boolean shiftWednesday, global::System.Boolean shiftThuersday, global::System.Boolean shiftFriday, global::System.Boolean shiftSaturday, global::System.Boolean shiftSunday, global::System.Int32 workingHours, global::System.Decimal breakTime)
        {
            Shift shift = new Shift();
            shift.ShiftID = shiftID;
            shift.ShiftName = shiftName;
            shift.ShiftMonday = shiftMonday;
            shift.ShiftTuesday = shiftTuesday;
            shift.ShiftWednesday = shiftWednesday;
            shift.ShiftThuersday = shiftThuersday;
            shift.ShiftFriday = shiftFriday;
            shift.ShiftSaturday = shiftSaturday;
            shift.ShiftSunday = shiftSunday;
            shift.WorkingHours = workingHours;
            shift.BreakTime = breakTime;
            return shift;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ShiftID
        {
            get
            {
                return _ShiftID;
            }
            set
            {
                if (_ShiftID != value)
                {
                    OnShiftIDChanging(value);
                    ReportPropertyChanging("ShiftID");
                    _ShiftID = StructuralObject.SetValidValue(value, "ShiftID");
                    ReportPropertyChanged("ShiftID");
                    OnShiftIDChanged();
                }
            }
        }
        private global::System.Int32 _ShiftID;
        partial void OnShiftIDChanging(global::System.Int32 value);
        partial void OnShiftIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ShiftName
        {
            get
            {
                return _ShiftName;
            }
            set
            {
                OnShiftNameChanging(value);
                ReportPropertyChanging("ShiftName");
                _ShiftName = StructuralObject.SetValidValue(value, false, "ShiftName");
                ReportPropertyChanged("ShiftName");
                OnShiftNameChanged();
            }
        }
        private global::System.String _ShiftName;
        partial void OnShiftNameChanging(global::System.String value);
        partial void OnShiftNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean ShiftMonday
        {
            get
            {
                return _ShiftMonday;
            }
            set
            {
                OnShiftMondayChanging(value);
                ReportPropertyChanging("ShiftMonday");
                _ShiftMonday = StructuralObject.SetValidValue(value, "ShiftMonday");
                ReportPropertyChanged("ShiftMonday");
                OnShiftMondayChanged();
            }
        }
        private global::System.Boolean _ShiftMonday;
        partial void OnShiftMondayChanging(global::System.Boolean value);
        partial void OnShiftMondayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean ShiftTuesday
        {
            get
            {
                return _ShiftTuesday;
            }
            set
            {
                OnShiftTuesdayChanging(value);
                ReportPropertyChanging("ShiftTuesday");
                _ShiftTuesday = StructuralObject.SetValidValue(value, "ShiftTuesday");
                ReportPropertyChanged("ShiftTuesday");
                OnShiftTuesdayChanged();
            }
        }
        private global::System.Boolean _ShiftTuesday;
        partial void OnShiftTuesdayChanging(global::System.Boolean value);
        partial void OnShiftTuesdayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean ShiftWednesday
        {
            get
            {
                return _ShiftWednesday;
            }
            set
            {
                OnShiftWednesdayChanging(value);
                ReportPropertyChanging("ShiftWednesday");
                _ShiftWednesday = StructuralObject.SetValidValue(value, "ShiftWednesday");
                ReportPropertyChanged("ShiftWednesday");
                OnShiftWednesdayChanged();
            }
        }
        private global::System.Boolean _ShiftWednesday;
        partial void OnShiftWednesdayChanging(global::System.Boolean value);
        partial void OnShiftWednesdayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean ShiftThuersday
        {
            get
            {
                return _ShiftThuersday;
            }
            set
            {
                OnShiftThuersdayChanging(value);
                ReportPropertyChanging("ShiftThuersday");
                _ShiftThuersday = StructuralObject.SetValidValue(value, "ShiftThuersday");
                ReportPropertyChanged("ShiftThuersday");
                OnShiftThuersdayChanged();
            }
        }
        private global::System.Boolean _ShiftThuersday;
        partial void OnShiftThuersdayChanging(global::System.Boolean value);
        partial void OnShiftThuersdayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean ShiftFriday
        {
            get
            {
                return _ShiftFriday;
            }
            set
            {
                OnShiftFridayChanging(value);
                ReportPropertyChanging("ShiftFriday");
                _ShiftFriday = StructuralObject.SetValidValue(value, "ShiftFriday");
                ReportPropertyChanged("ShiftFriday");
                OnShiftFridayChanged();
            }
        }
        private global::System.Boolean _ShiftFriday;
        partial void OnShiftFridayChanging(global::System.Boolean value);
        partial void OnShiftFridayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean ShiftSaturday
        {
            get
            {
                return _ShiftSaturday;
            }
            set
            {
                OnShiftSaturdayChanging(value);
                ReportPropertyChanging("ShiftSaturday");
                _ShiftSaturday = StructuralObject.SetValidValue(value, "ShiftSaturday");
                ReportPropertyChanged("ShiftSaturday");
                OnShiftSaturdayChanged();
            }
        }
        private global::System.Boolean _ShiftSaturday;
        partial void OnShiftSaturdayChanging(global::System.Boolean value);
        partial void OnShiftSaturdayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean ShiftSunday
        {
            get
            {
                return _ShiftSunday;
            }
            set
            {
                OnShiftSundayChanging(value);
                ReportPropertyChanging("ShiftSunday");
                _ShiftSunday = StructuralObject.SetValidValue(value, "ShiftSunday");
                ReportPropertyChanged("ShiftSunday");
                OnShiftSundayChanged();
            }
        }
        private global::System.Boolean _ShiftSunday;
        partial void OnShiftSundayChanging(global::System.Boolean value);
        partial void OnShiftSundayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 WorkingHours
        {
            get
            {
                return _WorkingHours;
            }
            set
            {
                OnWorkingHoursChanging(value);
                ReportPropertyChanging("WorkingHours");
                _WorkingHours = StructuralObject.SetValidValue(value, "WorkingHours");
                ReportPropertyChanged("WorkingHours");
                OnWorkingHoursChanged();
            }
        }
        private global::System.Int32 _WorkingHours;
        partial void OnWorkingHoursChanging(global::System.Int32 value);
        partial void OnWorkingHoursChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal BreakTime
        {
            get
            {
                return _BreakTime;
            }
            set
            {
                OnBreakTimeChanging(value);
                ReportPropertyChanging("BreakTime");
                _BreakTime = StructuralObject.SetValidValue(value, "BreakTime");
                ReportPropertyChanged("BreakTime");
                OnBreakTimeChanged();
            }
        }
        private global::System.Decimal _BreakTime;
        partial void OnBreakTimeChanging(global::System.Decimal value);
        partial void OnBreakTimeChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MojaModel", "FK_CardholderShift_Shift", "CardholderShift")]
        public EntityCollection<CardholderShift> CardholderShifts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CardholderShift>("MojaModel.FK_CardholderShift_Shift", "CardholderShift");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CardholderShift>("MojaModel.FK_CardholderShift_Shift", "CardholderShift", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
